OrdererOrgs:
  - Name: Orderer
    Domain: kaopiz.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.kaopiz.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.kaopiz.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.kaopiz.com
    Template:
      Count: 1
    Users:
      Count: 1